spring:
  security:
    oauth2:
      client:
        resourceserver:
          jwt:
            issuer-uri: ${LB_AUTH_ISSUER_URI:http://127.0.0.1:9000}
        registration:
          msvc-usuarios-client:
            provider: spring
            client-id: usuarios-client
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: ${LB_USUARIOS_URI:http://127.0.0.1:8001}/authorized
            scope: read
            client-name: msvc-usuarios-client
        provider:
          spring:
            issuer-uri: ${LB_AUTH_ISSUER_URI:http://127.0.0.1:9000}